language: node_js
node_js:
- '6.1'
deploy:
  provider: npm
  email: sebastian@urbantalk.se
  api_key:
    secure: SPI8Pn1enajPyhbTtbyff89NTs+bQxeefHEnkco1fuB6FhTLR9AcY2jEqf0fDaGiSL0+9xT0sGyr73FQge4Egfb2YLmmOyRwIZMTvKahmuMm7QvvKGch82KdocrTy6mLKHnB183lYVcnVOBAnnsESueYv1oPks8uRI9jvwxjgheXL+hJObU8tsYCV9paOhTpv5/w7QMMibuBJ0nGU9TVT+I79vnMWW+z2e0Dtl6NZ1vi3+Q/ywL+c1/0wE4cSIupjK1R8abeHO/A9F8kTwUkvxeZzK0wsm76qTN09QQHJfRJMvwMuac5rQfOTXIsX6A7KN2001o0d0OekO5BijuYOSjAxkV7h/A3g7/cZ5LRVbFNo5nsEXvQpRMW54697ysO3pTCbAsuVYypGgZUk8op/2on474p4p89ot2Pv7eCNKVkzr48EOKNhrJ9d0AWmv+29dA+mMTz3kMqFI7b2PFmIdYe5oZVBkArDBy491W+sXdCuREH+BxXvGJ5UzeuTTYjA+DqY92abDHhRNEBbzNuIrWA6nKeq5hG/LadzVFbeKQTkdXiAK7qxAa8p80PQgqfp/tyRkOEeGe65jfmG15hMINyoRrHcL6gTJn0EeZfNU66NZrZhhnJwuVBR1sYcfwG9ONA8LgqlHMxiiSC6pPq3ZFsB5w2zM3mlcSgmQ6zcGA=
  on:
    tags: true
    repo: jhsware/inferno-formlib
